CHAIN_TO_RELATION  = {
"R(M).S(M)":"Father",
"R(M).D(F)":"Father",
"R(M).S(M).D(F)":"Grand Father",
"R(M).S(M).S(M)":"Grand Father",
"R(M).D(F).D(F)":"Grand Father",
"R(M).D(F).S(M)":"Grand Father",
"R(M).S(M).D(F).S(M)":"Grand Father",
"R(M).S(M).D(F).D(F)":"Grand Father",
"R(M).S(M).S(M).D(F)":"Paternal Great Grand Father",
"R(M).S(M).S(M).S(M)":"Paternal Great Grand Father",
"R(M).D(F).D(F).S(M)":"Maternal Great Grand Father",
"R(M).D(F).D(F).D(F)":"Maternal Great Grand Father",
"R(M).D(F).S(M).D(F)":"Maternal Great Grand Father",
"R(M).D(F).S(M).S(M)":"Maternal Great Grand Father",
"R(M).S(M).S(M).W(F)":"Father of Father-in-law",
"R(M).S(M).S(M).W(F).F(M)":"Father of Father-in-law",
"R(M).S(M).S(M).W(F).F(M).D(F)":"Extended Relatives",
"R(M).S(M).S(M).W(F).F(M).S(M)":"Extended Relatives",
"R(M).S(M).S(M).W(F).F(M).D(F).S(M)":"Extended Relatives",
"R(M).S(M).S(M).W(F).F(M).D(F).H(M)":"Extended Relatives",
"R(M).S(M).S(M).W(F).F(M).D(F).D(F)":"Extended Relatives",
"R(M).S(M).S(M).W(F).F(M).D(F).S(M).W(F)":"Extended Relatives",
"S(M).R(M)":"SON",
"S(M).R(M).S(M)":"Cousin/Brother",
"S(M).R(M).D(F)":"Cousin/Brother",
"S(M).D(F)":"Father",
"S(M).S(M)":"Father",
"S(M).R(M).S(M).D(F)":"Babai/Pedhananna",
"S(M).R(M).S(M).S(M)":"Babai/Pedhananna",
"S(M).R(M).D(F).D(F)":"Maternal Uncle",
"S(M).R(M).D(F).S(M)":"Maternal Uncle",
"S(M).D(F).S(M)":"Maternal Grand Father",
"S(M).D(F).D(F)":"Maternal Grand Father",
"S(M).S(M).D(F)":"Paternal Grand Father",
"S(M).S(M).S(M)":"Paternal Grand Father",
"S(M).R(M).S(M).D(F).S(M)":"Grand Father",
"S(M).R(M).S(M).D(F).D(F)":"Grand Father",
"S(M).R(M).S(M).S(M).D(F)":"Grand Father",
"S(M).R(M).S(M).S(M).S(M)":"Grand Father",
"S(M).R(M).D(F).D(F).S(M)":"Grand Father",
"S(M).R(M).D(F).D(F).D(F)":"Grand Father",
"S(M).R(M).D(F).S(M).D(F)":"Grand Father",
"S(M).R(M).D(F).S(M).S(M)":"Grand Father",
"S(M).S(M).W(F)":"Father-in-law(Husband's Father)",
"S(M).S(M).W(F).F(M)":"Co-father-in-law(Viyyankudu)",
"S(M).S(M).W(F).F(M).D(F)":"Father-in-law",
"S(M).S(M).W(F).F(M).S(M)":"Father-in-law",
"S(M).S(M).W(F).F(M).D(F).S(M)":"Grand Father",
"S(M).S(M).W(F).F(M).D(F).H(M)":"Babai/Pedha Nanna",
"S(M).S(M).W(F).F(M).D(F).D(F)":"Grand Father",
"S(M).S(M).W(F).F(M).D(F).S(M).W(F)":"Extended Relatives",
"S(M).R(M).S(M).S(M).W(F)":"Father-in-law",
"S(M).R(M).S(M).S(M).W(F).F(M)":"Co-father-in-law(Viyyankudu)",
"S(M).R(M).S(M).S(M).W(F).F(M).D(F)":"Father-in-law",
"S(M).R(M).S(M).S(M).W(F).F(M).S(M)":"Father-in-law",
"S(M).R(M).S(M).S(M).W(F).F(M).D(F).S(M)":"Grand Father",
"S(M).R(M).S(M).S(M).W(F).F(M).D(F).H(M)":"Babai/Pedha Nanna",
"S(M).R(M).S(M).S(M).W(F).F(M).D(F).D(F)":"Grand Father",
"S(M).R(M).S(M).S(M).W(F).F(M).D(F).S(M).W(F)":"Extended Relatives",
"D(F).R(M)":"Daughter",
"D(F).R(M).S(M)":"Cousin/Sister",
"D(F).R(M).D(F)":"Cousin/Sister",
"D(F).R(M).S(M).D(F)":"Maternal Aunt",
"D(F).R(M).S(M).S(M)":"Maternal Aunt",
"D(F).D(F)":"Mother",
"D(F).S(M)":"Mother",
"D(F).R(M).D(F).S(M)":"Pinni/Pedhamma",
"D(F).R(M).S(M).D(F).S(M)":"Grand Mother",
"D(F).R(M).S(M).D(F).D(F)":"Grand Mother",
"D(F).R(M).S(M).S(M).D(F)":"Grand Mother",
"D(F).R(M).S(M).S(M).S(M)":"Grand Mother",
"D(F).D(F).S(M)":"Maternal Grand Mother",
"D(F).D(F).D(F)":"Maternal Grand Mother",
"D(F).S(M).D(F)":"Paternal Grand Mother",
"D(F).R(M).D(F).S(M).D(F)":"Grand Mother",
"D(F).R(M).D(F).S(M).S(M)":"Grand Mother",
"D(F).R(M).S(M).S(M).W(F)":"Pinni/Pedhamma",
"D(F).R(M).S(M).S(M).W(F).F(M)":"Extended Relatives",
"D(F).R(M).S(M).S(M).W(F).F(M).D(F)":"Pinni/Pedhamma",
"D(F).R(M).S(M).S(M).W(F).F(M).S(M)":"Pinni/Pedhamma",
"D(F).R(M).S(M).S(M).W(F).F(M).D(F).S(M)":"Grand Mother",
"D(F).R(M).S(M).S(M).W(F).F(M).D(F).H(M)":"Aunt",
"D(F).R(M).S(M).S(M).W(F).F(M).D(F).D(F)":"Grand Mother",
"D(F).R(M).S(M).S(M).W(F).F(M).D(F).S(M).W(F)":"Extended Relatives",
"D(F).R(M).D(F).D(F)":"Pinni/Pedhamma",
"D(F).R(M).D(F).D(F).S(M)":"Grand Mother",
"D(F).R(M).D(F).D(F).D(F)":"Grand Mother",
"D(F).S(M).S(M)":"Paternal Grand Mother",
"D(F).S(M).R(M)":"Grand Daughter",
"D(F).S(M).R(M).S(M)":"brother's daughter / niece",
"D(F).S(M).R(M).D(F)":"Daughter-in-law",
"D(F).S(M).R(M).S(M).D(F)":"Cousin/Sister",
"D(F).S(M).R(M).S(M).S(M)":"Cousin/Brother",
"D(F).S(M).R(M).D(F).D(F)":"Sister-in-law",
"D(F).S(M).R(M).D(F).S(M)":"Sister-in-law",
"D(F).S(M).S(M).D(F)":"Paternal Aunt",
"D(F).S(M).S(M).S(M)":"Paternal Aunt",
"D(F).S(M).R(M).S(M).D(F).S(M)":"Pinni/Pedhamma",
"D(F).S(M).R(M).S(M).D(F).D(F)":"Pinni/Pedhamma",
"D(F).S(M).R(M).S(M).S(M).D(F)":"Athayya",
"D(F).S(M).R(M).S(M).S(M).S(M)":"Athayya",
"D(F).S(M).R(M).D(F).D(F).S(M)":"Athayya",
"D(F).S(M).R(M).D(F).D(F).D(F)":"Athayya",
"D(F).S(M).R(M).D(F).S(M).D(F)":"Athayya",
"D(F).S(M).R(M).D(F).S(M).S(M)":"Pinni/Pedhamma",
"D(F).S(M).S(M).W(F)":"Sister-in-law",
"D(F).S(M).S(M).W(F).F(M)":"Daughter-in-law",
"D(F).S(M).S(M).W(F).F(M).D(F)":"Sister-in-law",
"D(F).S(M).S(M).W(F).F(M).S(M)":"Sister-in-law",
"D(F).S(M).S(M).W(F).F(M).D(F).S(M)":"Athayya",
"D(F).S(M).S(M).W(F).F(M).D(F).H(M)":"Cousin/Sister",
"D(F).S(M).S(M).W(F).F(M).D(F).D(F)":"Athayya",
"D(F).S(M).S(M).W(F).F(M).D(F).S(M).W(F)":"Extended Relatives",
"S(M).S(M).R(M)":"Grand Son",
"S(M).S(M).R(M).S(M)":"brother's son/Nephew",
"S(M).S(M).R(M).D(F)":"Maternal Aunt",
"S(M).S(M).R(M).S(M).D(F)":"Cousin/Brother",
"S(M).S(M).R(M).S(M).S(M)":"Cousin/Brother",
"S(M).S(M).R(M).D(F).D(F)":"Brother-in-law",
"S(M).S(M).R(M).D(F).S(M)":"Brother-in-law",
"S(M).S(M).D(F).S(M)":"Maternal Uncle",
"S(M).S(M).D(F).D(F)":"Maternal Uncle",
"S(M).S(M).R(M).S(M).D(F).S(M)":"Father-in-law",
"S(M).S(M).R(M).S(M).D(F).D(F)":"Father-in-law",
"S(M).S(M).R(M).S(M).S(M).D(F)":"Babai/Pedha Nanna",
"S(M).S(M).R(M).S(M).S(M).S(M)":"Babai/Pedha Nanna",
"S(M).S(M).R(M).D(F).D(F).S(M)":"Babai/Pedha Nanna",
"S(M).S(M).R(M).D(F).D(F).D(F)":"Babai/Pedha Nanna",
"S(M).S(M).R(M).D(F).S(M).D(F)":"Father-in-law",
"S(M).S(M).R(M).D(F).S(M).S(M)":"Father-in-law",
"S(M).W(F)":"Husband",
"S(M).W(F).F(M)":"Son-in-law",
"S(M).W(F).F(M).D(F)":"Brother-in-law",
"S(M).W(F).F(M).S(M)":"Brother-in-law",
"S(M).W(F).F(M).D(F).S(M)":"Babai/Pedha Nanna",
"S(M).W(F).F(M).D(F).H(M)":"Co-Brother",
"S(M).W(F).F(M).D(F).D(F)":"Babai/Pedha Nanna",
"S(M).W(F).F(M).D(F).S(M).W(F)":"Father-in-law",
"D(F).S(M).R(M).S(M).S(M).W(F)":"Sister-in-law",
"D(F).S(M).R(M).S(M).S(M).W(F).F(M)":"Daughter-in-law",
"D(F).S(M).R(M).S(M).S(M).W(F).F(M).D(F)":"Sister-in-law",
"D(F).S(M).R(M).S(M).S(M).W(F).F(M).S(M)":"Sister-in-law",
"D(F).S(M).R(M).S(M).S(M).W(F).F(M).D(F).S(M)":"Athayya",
"D(F).S(M).R(M).S(M).S(M).W(F).F(M).D(F).H(M)":"Cousin/Sister",
"D(F).S(M).R(M).S(M).S(M).W(F).F(M).D(F).D(F)":"Athayya",
"D(F).S(M).R(M).S(M).S(M).W(F).F(M).D(F).S(M).W(F)":"Extended Relatives",
"S(M).S(M).S(M).D(F)":"Babai/Pedha Nanna",
"S(M).S(M).R(M).S(M).S(M).W(F)":"Brother-in-law",
"S(M).S(M).R(M).S(M).S(M).W(F).F(M)":"Son-in-law",
"S(M).S(M).R(M).S(M).S(M).W(F).F(M).D(F)":"Brother-in-law",
"S(M).S(M).R(M).S(M).S(M).W(F).F(M).S(M)":"Brother-in-law",
"S(M).S(M).R(M).S(M).S(M).W(F).F(M).D(F).S(M)":"Babai/Pedha Nanna",
"S(M).S(M).R(M).S(M).S(M).W(F).F(M).D(F).H(M)":"Cousin/Brother",
"S(M).S(M).R(M).S(M).S(M).W(F).F(M).D(F).D(F)":"Babai/Pedha Nanna",
"S(M).S(M).R(M).S(M).S(M).W(F).F(M).D(F).S(M).W(F)":"Extended Relatives",
"S(M).S(M).S(M).S(M)":"Babai/Pedha Nanna",
"D(F).D(F).R(M)":"Sister-in-law",
"D(F).D(F).R(M).S(M)":"Niece",
"D(F).D(F).R(M).D(F)":"Niece",
"D(F).D(F).R(M).S(M).D(F)":"Sister-in-law",
"D(F).D(F).R(M).S(M).S(M)":"Sister-in-law",
"D(F).D(F).R(M).D(F).S(M)":"Cousin/Sister",
"D(F).D(F).R(M).S(M).D(F).S(M)":"Athayya",
"D(F).D(F).R(M).S(M).D(F).D(F)":"Athayya",
"D(F).D(F).R(M).S(M).S(M).D(F)":"Pinni/Pedhamma",
"D(F).D(F).R(M).S(M).S(M).S(M)":"Pinni/Pedhamma",
"D(F).D(F).D(F).S(M)":"Pinni/Pedhamma",
"D(F).D(F).D(F).D(F)":"Pinni/Pedhamma",
"D(F).D(F).S(M).D(F)":"Maternal Aunt",
"D(F).D(F).R(M).D(F).S(M).D(F)":"Athayya",
"D(F).D(F).R(M).D(F).S(M).S(M)":"Athayya",
"D(F).D(F).R(M).S(M).S(M).W(F)":"Cousin/Sister",
"D(F).D(F).R(M).S(M).S(M).W(F).F(M)":"Niece",
"D(F).D(F).R(M).S(M).S(M).W(F).F(M).D(F)":"Cousin/Sister",
"D(F).D(F).R(M).S(M).S(M).W(F).F(M).S(M)":"Cousin/Sister",
"D(F).D(F).R(M).S(M).S(M).W(F).F(M).D(F).S(M)":"Pinni/Pedhamma",
"D(F).D(F).R(M).S(M).S(M).W(F).F(M).D(F).H(M)":"Sister-in-law",
"D(F).D(F).R(M).S(M).S(M).W(F).F(M).D(F).D(F)":"Pinni/Pedhamma",
"D(F).D(F).R(M).S(M).S(M).W(F).F(M).D(F).S(M).W(F)":"Extended Relatives",
"S(M).D(F).R(M)":"Grand Son",
"S(M).D(F).R(M).S(M)":"Menalludu",
"S(M).D(F).R(M).D(F)":"Niece",
"S(M).D(F).R(M).S(M).D(F)":"Brother-in-law",
"S(M).D(F).R(M).S(M).S(M)":"Brother-in-law",
"S(M).D(F).R(M).D(F).S(M)":"Cousin/Brother",
"S(M).D(F).R(M).S(M).D(F).S(M)":"Babai/Pedhanna",
"S(M).D(F).R(M).S(M).D(F).D(F)":"Babai/Pedhanna",
"S(M).D(F).R(M).S(M).S(M).D(F)":"Babai/Pedhanna",
"S(M).D(F).R(M).S(M).S(M).S(M)":"Father-in-law",
"S(M).D(F).D(F).S(M)":"Maternal Uncle/ Menamama",
"S(M).D(F).D(F).D(F)":"Maternal Uncle/ Menamama",
"S(M).D(F).R(M).D(F).S(M).D(F)":"Babai/Pedhananna",
"S(M).D(F).R(M).D(F).S(M).S(M)":"Babai/Pedhananna",
"S(M).D(F).R(M).S(M).S(M).W(F)":"Cousin/Brother",
"S(M).D(F).R(M).S(M).S(M).W(F).F(M)":"Extended Relatives",
"S(M).D(F).R(M).S(M).S(M).W(F).F(M).D(F)":"Cousin/Brother",
"S(M).D(F).R(M).S(M).S(M).W(F).F(M).S(M)":"Cousin/Brother",
"S(M).D(F).R(M).S(M).S(M).W(F).F(M).D(F).S(M)":"Father-in-law",
"S(M).D(F).R(M).S(M).S(M).W(F).F(M).D(F).H(M)":"Brother-in-law",
"S(M).D(F).R(M).S(M).S(M).W(F).F(M).D(F).D(F)":"Father-in-law",
"S(M).D(F).R(M).S(M).S(M).W(F).F(M).D(F).S(M).W(F)":"Extended Relatives",
"S(M).D(F).R(M).D(F).D(F)":"Cousin/Brother",
"S(M).D(F).R(M).D(F).D(F).S(M)":"Father-in-law",
"S(M).D(F).R(M).D(F).D(F).D(F)":"Father-in-law",
"S(M).D(F).S(M).S(M)":"Babai/Pedhananna",
"S(M).D(F).S(M).D(F)":"Babai/Pedhananna",
"S(M).D(F).S(M).R(M)":"Maternal Great Grand Son",
"S(M).D(F).S(M).R(M).S(M)":"Maternal Grand Son",
"S(M).D(F).S(M).R(M).D(F)":"Maternal Grand Son",
"S(M).D(F).S(M).R(M).S(M).D(F)":"Nephew",
"S(M).D(F).S(M).R(M).S(M).S(M)":"Son-in-law",
####
"S(M).D(F).S(M).R(M).D(F).D(F)":"Son-in-law",
"D(F).F(M).W(F).S(M)":"Sister-in-law/Vadhina",
"R(M).S(M)":"Father",
"R(M).D(F)":"Father",
"S(M).D(F)":"Son",
"S(M).R(M)":"Son",
"D(F).R(M)":"Daughter",
"D(F).S(M)":"Mother",
"D(F).D(F)":"Mother",
"W(F).S(M).D(F)":"Mother",
"W(F).S(M).S(M)":"Mother",
"S(M).S(M).W(F)":"Son",
"D(F).R(M).S(M)":"Sister",
"D(F).F(M).W(F)":"Sister",
"W(F).F(M).D(F)":"Sister",
"W(F).F(M).D(F).H(M)":"Maradhalu/Daughter-in-law",
"H(M).D(F).F(M).W(F)":"Bava/Brother-in-law",
"D(F).D(F).S(M)":"Sister",
"S(M).D(F).D(F)":"Brother",
"D(F).S(M).W(F)":"Daughter",
"S(M).S(M).D(F)":"Brother",
"S(M).S(M).S(M)":"Brother",
"S(M).R(M).S(M)":"Brother",
"S(M).S(M).R(M).S(M).S(M)":"Brother",
"S(M).S(M).R(M).S(M).D(F)":"Brother",
"S(M).R(M).D(F)":"Brother",
"W(F).S(M)":"Wife",
"D(F).H(M)":"Wife",
"M(F).S(M).S(M)":"Husband",
"M(F).D(F).S(M)":"Wife",
"W(F).R(M)":"Husband",
"S(M).W(F)":"Husband",
"H(M).D(F)":"Husband",
"F(M).S(M).D(F)":"Wife",
"F(M).D(F).D(F)":"Wife",
"R(M).W(F)":"Wife"
}